image: alpine:3.20.2

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH != "main" && $CI_PIPELINE_SOURCE != "merge_request_event"      
      when: never
    - when: always

stages:
  - test
  - build
  - deploy

variables:
  image_repository: docker.io/my-docker-id/myapp
  image_tag: v1.0

run_unit_tests:
  image: node:22-alpine3.19
  tags:
    - ec2 
    - docker 
    - remote
  stage: test
  before_script:
    - echo "Preparing test data..."
  script:
    - echo "Running unit tests for micro service $MICRO_SERVICE_NAME ..."
    - npm version
  after_script:
    - echo "Cleaning up temporary files..."

run_lint_tests:
  tags:
    - ec2 
    - shell
    - remote
  stage: test
  before_script:
    - echo "Preparing test data..."
  script:
    - echo "Running lint tests for micro service $MICRO_SERVICE_NAME ..."
  after_script:
    - echo "Cleaning up temporary files..."


build_image:
  tags:
    - ec2 
    - shell
    - remote
  only:
    - main
  stage: build
  script: 
    - echo "Building the docker image..."
    - echo "Tagging the docker image $image_repository:$image_tag ..."

push_image:
  tags:
    - ec2 
    - shell
    - remote
  only:
    - main
  stage: build
  needs: 
    - build_image
  script: 
    - echo "Logging into docker registry..."
    - echo "Pushing docker image $image_repository:$image_tag  to registry..."

deploy_image:
  tags:
    - ec2 
    - shell 
    - remote
  only:
    - main
  stage: deploy
  script: 
    - echo "Deploying docker image $image_repository:$image_tag to dev server..."       
    - echo "Deploying docker image to $DEPLOYMENT_ENVIRONMENT using the following configuration file - $PROPERTIES_FILE..."
    - cat $PROPERTIES_FILE



