run_tests:
  before_script:
    - echo "preparing test data..."
  script:
    - echo "runing tests..."
  after_script:
    - echo "Cleaning the temporary files..."

build_image:
  script:
    - echo "build the docker images.."
    - echo "tagging the docker images.."

push_image:
  script:
    - echo "logging the docker registry.."
    - echo "pushing docker image to registry.."


