workflow:
  rules:
    - if: $CI_COMMIT_BRANCH != "main" && $CI_PIPELINE_SOURCE != "merge_request_event"
      when: never
    - when: always


run_unit_test:
  image: 20-alpine3.17
  tags:
    - ec2 
    - docker
    - remote
  before_script:
    - cd app 
    - npm install 
  script:
    - npm test