workflow:
  rules:
    - if: $CI_COMMIT_BRANCH != "main" && $CI_PIPELINE_SOURCE != "merge_request_event"
      when: never
    - when: always

stages:
  - test 
  - build

run_unit_test:
  image: node:22-alpine3.19
  stage: test
  tags:
    - ec2 
    - docker
    - remote
  before_script:
    - cd app
    - npm install
  script:
    - npm test
  artifacts:
    when: always
    reports:
      junit: app/junit.xml

build_image:
  stage: build
  tags:
    - ec2 
    - shell
    - remote
  script:
    - docker build -t $CI_REGISTRY_IMAGE:1.0 .

push_image:
  stage: build
  needs:
    - build_image
  tags:
    - ec2
    - shell
    - remote
  before_script:
    - echo "Docker registry url is $CI_REGISTRY"
    - echo "Docker registry username is $CI_REGISTRY_USER"
    - echo "Docker registry image repo is $CI_REGISTRY_IMAGE"
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin  $CI_REGISTRY
  script:
    - docker push $CI_REGISTRY_IMAGE:1.0