workflow:
  rules:
    - if: $CI_COMMIT_BRANCH != "main" && $CI_PIPELINE_SOURCE != "merge_request_event"
      when: never
    - when: always

variables:
  IMAGE_NAME: $CI_REGISTRY_IMAGE
  DEV_SERVER_HOST: 18.191.159.112
  DEV_ENDPOINT: http://ec2-18-191-159-112.us-east-2.compute.amazonaws.com:3000

stages:
  - test 
  - build
  - deploy

run_unit_test:
  image: node:22-alpine3.19
  stage: test
  tags:
    - ec2 
    - remote
    - docker
  before_script:
    - cd app 
    - npm install
  script:
    - npm test
  artifacts:
    when: always
    reports:
      junit: app/junit.xml

build_image:
  stage: build
  tags:
    - ec2 
    - shell 
    - remote
  before_script:
    - export PACKAGE_JSON_VERSION=$(cat app/package.json | jq -r .version)
    - export VERSION=$PACKAGE_JSON_VERSION.$CI_PIPELINE_IID
    - echo $VERSION > version-file.txt
  script:
    - docker build -t $IMAGE_NAME:$VERSION .
  artifacts:
    paths:
      - version-file.txt

push_image:
  stage: build
  needs:
    - build_image
  dependencies:
    - build_image
  tags:
    - ec2 
    - shell 
    - remote
  before_script:
    - export VERSION=$(cat version-file.txt)
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  script:
    - docker push $IMAGE_NAME:$VERSION

deploy_to_dev:
  stage: deploy
  tags:
    - ec2 
    - shell
    - remote
  before_script:
    - chmod 400 $SSH_PRIVATE_KEY
    - export VERSION=$(cat version-file.txt)
  script:
    - scp -o StrictHostKeyChecking=no -i $SSH_PRIVATE_KEY ./docker-compose.yaml ubuntu@$DEV_SERVER_HOST:/home/ubuntu
    - ssh -o StrictHostKeyChecking=no -i $SSH_PRIVATE_KEY ubuntu@$DEV_SERVER_HOST "
       echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY &&

       export DC_IMAGE_NAME=$IMAGE_NAME &&
       export DC_IMAGE_TAG=$VERSION &&

       docker-compose down &&
       docker-compose up -d"
  environment:
    name: deployment 
    url: $DEV_ENDPOINT